### ISSUE TITLE
Encountering WSoD with Drupal 8.2.4

### ISSUE THREAD

**Issue by tony-o** [adriangordon1231/anonymous_redirect#1]
Steps to reproduce:

1. Install D8
2. Install `anonymous_redirect`
3. Enable module
4. Logout
5. Enjoy the WSoD (you can log back in by visiting `/user/login`)

**Comment by adriangordon1231** [comment]
Hmmm. Really. I will look into this.

**Comment by adriangordon1231** [comment]
I am sorry, I just cannot reproduce this issue. The whitescreen of death you are seeing is likely not related to this module.

**Comment by tony-o** [comment]
Enabling this module by itself on 8.2.4 causes the issue.

Sent from my iPhone

On Jan 15, 2017, at 1:37 PM, Adrian Gordon <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #1<https://github.com/adriangordon1231/anonymous_redirect/issues/1>.

-
